prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 15s
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
    probeNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

grafana:
  defaultDashboardsTimezone: browser
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      editable: true
      isDefault: false
      jsonData:
        maxLines: 2000

alertmanager:
  alertmanagerSpec:
    replicas: 1
