services:
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    restart: unless-stopped
    user: "0:0"
    environment:
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_USER:-admin}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD:-}
      JENKINS_PUBLIC_URL: ${JENKINS_PUBLIC_URL:-}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-}
      JENKINS_MULTIBRANCH_JOB: ${JENKINS_MULTIBRANCH_JOB:-my-app-mb}
      JENKINS_MULTIBRANCH_SCAN_INTERVAL: ${JENKINS_MULTIBRANCH_SCAN_INTERVAL:-2m}
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./.jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
