apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret-sync
  namespace: my-app
spec:
  secretStoreRef:
    name: k8s-secret-store # This store points to the k8s api
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: app-secret
    creationPolicy: 'Owner'
    template:
      engine: gotpl
      data:
        # postgresql://user:password@host:port/dbname
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@{{ .POSTGRES_HOST }}:{{ .POSTGRES_PORT }}/{{ .POSTGRES_DB }}"
  dataFrom:
  - extract:
      key: postgres-secret
  - extract:
      key: app-config
      kind: ConfigMap
