apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret-sync
  namespace: my-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: k8s-secret-store
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: postgres-secret
    creationPolicy: 'Owner'
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: postgres-credentials-source
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: postgres-credentials-source
      property: POSTGRES_PASSWORD
  - secretKey: POSTGRES_DB
    remoteRef:
      key: postgres-credentials-source
      property: POSTGRES_DB
