apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-secret-store
  namespace: my-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-secret-reader
          namespace: my-app
