apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s-secret-store
  namespace: my-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    kubernetes:
      remoteNamespace: my-app
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-secret-reader
          namespace: my-app
