apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: my-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: my-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: worker
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 192Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: my-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 192Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  namespace: my-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: simulator
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 192Mi
