[alembic]
script_location = alembic
sqlalchemy.url = postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
# This will be dynamically set using env variables or a secret

[post_write_hooks]
# post_write_hooks =
